version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: scrolladexAdmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrolladex
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: 
      context: ./scrolladex-be
    volumes:
      - ./scrolladex-be:/usr/src/app:delegated
      - ./scrolladex-be/public/uploads:/usr/src/app/public/uploads
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - db
  frontend:
    build:
      context: ./scrolladex-fe
    volumes:
      - ./scrolladex-fe:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/ssl:/etc/ssl/certs
      - ./scrolladex-be/public:/usr/src/nginx/public
    depends_on:
      - frontend
      - backend
volumes:
  db-data:
